package com.mdlive.unifiedmiddleware.commonclasses.constants;

/**
 * Created by unnikrishnan_b on 5/5/2015.
 */
public class PreferenceConstants {
    public static final String MDLIVE_USER_PREFERENCES = "MDLIVE_USER_PREFERENCES";
    public static final String USER_PREFERENCES = "USER_PREFERENCES";
    public static final String PAY_AMOUNT_PREFERENCES = "AMOUNT_PREFERENCES";
    public static final String REASON_PREFERENCES = "REASON_FOR_VISIT";
    public static final String USER_UNIQUE_ID = "USER_UNIQUE_ID";
    public static final String DEPENDENT_USER_ID = "DEPENDENT_USER_ID";
    public static final String ZIPCODE_PREFERENCES = "ZIPCODE_PREFERENCES";
    public static final String LONGNAME_LOCATION_PREFERENCES = "LONGNAME_LOCATION_PREFERENCES";
    public static final String SEARCHFILTER_LONGNAME_LOCATION_PREFERENCES = "LONGNAME_LOCATION_PREFERENCES";
    public static final String PROVIDER_DOCTORID_PREFERENCES = "DOCTORID_PREFERENCES";
    public static final String PROVIDER_APPOINTMENT_DATE_PREFERENCES = "APPOINTMENT_DATE_PREFERENCES";
    public static final String PROVIDER_GROUP_AFFILIATIONS_PREFERENCES = "GROUP_AFFILIATIONS_PREFERENCES";
    public static final String PROVIDER_AVAILABILITY_TYPE_PREFERENCES = "AVAILABILITY_TYPE_PREFERENCES";
    public static final String PROVIDER_AVAILABILITY_STATUS_PREFERENCES = "AVAILABILITY_STATUS_PREFERENCES";
    public static final String TIMEZONE_PREF = "TIMEZONE_PREF";
    public static final String PEDIATRIC_IMMUNISATION_PREF = "PEDIATRIC_IMMUNISATION_PREF";
    public static final String PEDIATRIC_BIRTH_PREF = "PEDIATRIC_BIRTH_PREF";
    public static final String PEDIATRIC_CHILD_PREF = "PEDIATRIC_CHILD_PREF";
    public static final String DATE_OF_BIRTH = "DATE_OF_BIRTH";
    public static final String APPT_ID = "APPT_ID";
    public static final String PATIENT_NAME = "patient_name";
    public static final String AMOUNT = "payable_amount";
    public static final String OFFER_CODE = "offer_code";
    public static final String EXISTING_CARD_CHECK = "existing_card_check";
    public static final String REASON = "visit_reason";
    public static final String GENDER = "gender";
    public static final String PROVIDER_TYPE = "provider_type";
    public static final String PROVIDER_MODE = "provider_mode";
    public static final String CONSULTATION_TYPE = "consultation_type";
    public static final String SELECTED_TIMESLOT = "selected_timeslot";
    public static final String SELECTED_TIMESTAMP = "selected_timestamp";
    public static final String IDEAL_DATE = "ideal_date";
    public static final String NEXT_AVAIL_DATE = "next_avail_date";
    public static final String SELECTED_DATE = "selected_date";
    public static final String SELECTED_PHYSID = "selected_physid";
    public static final String PROVIDER_PROFILE = "provider_profile";
    public static final String APPOINTMENT_TYPE = "appointment_type";
    public static final String ACCESS_MODE = "access_mode";
    public static final String PHONE_NUMBER = "phone_number";
    public static final String PROVIDERTYPE_ID = "providertype_id";
    public static final String PHOTOS_COLLECTION = "PHOTOS_COLLECTION";
    public static final String LOCATION = "location";
    public static final String PROVIDER_DOCTORNANME_PREFERENCES = "DOCTORNAME_PREFERENCES";
    public static final String USER_BASIC_INFO = "USER_BASIC_INFO";
    public static final String USER = "USER";
    public static final String PENDING_APPOINMENT = "PENDING_APPOINMENT";
    public static final String APPOINMENT = "APPOINMENT";
    public static final String PREFFERED_SIGNIN = "Preffered_SignIn";
    public static final String PREFFERED_LANGUAGE = "Preffered_Language";
    public static final String SIGN_IN = "Sign_In";
    public static final String LOCK_TYPE = "Lock_Type";
    public static final String TIME_PREFERENCE = "TIME_PREFERENCE";
    public static final String TIME_KEY = "TIME_KEY";
    public static final String SELECTED_USER = "SELECTED_USER";
    public static final String DEVICE_OS = "DEVICE_OS";
    public static final String DEVICE_OS_KEY = "DEVICE_OS_KEY";
    public static final String DEVICE_ID = "device_id";
    public static final String DEVICE_ID_KEY = "device_id";
    public static final String DEVICE_TOKEN = "device_token";
    public static final String USER_STATE_LIST = "USER_STATE_LIST";
    public static final String HEALTH_SYSTEM_PREFERENCES = "HEALTH_SYSTEM_PREFERENCES";
    public static final String FIRST_TIME = "FIRST_TIME";
    public static final String PRIMARY_PHYSICIAN_STATUS = "PRIMARY_PHYSICIAN_STATUS";
    public static final String GOOGLE_FIT_PREFERENCES = "GOOGLE_FIT_PREFERENCES";
    public static final String GOOGLE_FIT_FIRST_TIME = "GOOGLE_FIT_FIRST_TIME";
    public static final String BAYLOR_GUID = "baylor_guid";
}
